# Generated by Django 5.1.5 on 2025-01-28 13:06

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inference", "pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=256)),
                ("pos", models.CharField(max_length=32)),
                ("embedding", pgvector.django.vector.VectorField(dimensions=768)),
            ],
        ),
    ]
